install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
    # Informations
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    - ldd -v
addons:
    apt:
        sources:
            - llvm-toolchain-precise-3.7
            - ubuntu-toolchain-r-test
        packages:
            - clang-3.7
            - g++-4.8
            - gcc-4.8
            - libc6
            - valgrind
            - cmake
language: cpp
compiler:
  - clang
  - gcc
before_script:
  - git submodule init
  - git submodule update
script:
  - mkdir build
  - cd build
  - cmake ..
  - make clean
  - make
  - valgrind --leak-check=full --track-origins=yes ./sandbox/tests/sandbox_tests
