language: cpp
compiler:
  - clang
  - gcc
os:
 - linux
include:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
    env:
       - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
          - llvm-toolchain-precise-3.7
        packages:
          - clang-3.7
    env:
      - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"
  - os: linux
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
    env:
      - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
addons:
    apt:
        packages:
            - valgrind
            - cmake
before_install:
    - eval "${MATRIX_EVAL}"
before_script:
  - git submodule init
  - git submodule update
script:
  - mkdir build
  - cd build
  - cmake ..
  - make clean
  - make
  - valgrind --leak-check=full --track-origins=yes ./sandbox/tests/sandbox_tests
