language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env:
        - MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: osx
before_install:
    - eval "${MATRIX_EVAL}"
install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install cmake; fi
before_script:
  - git submodule init
  - git submodule update
script:
  - mkdir build
  - cd build
  - cmake ..
  - make clean
  - make
  - ./fpcontrol/tests/fpcontrol_tests
